// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxGrYnulA75uTssdpsTcqDckLLsZrHJo',
    appId: '1:686535225133:web:05d32bc28bb29b86aaada4',
    messagingSenderId: '686535225133',
    projectId: 'turismapp-776f3',
    authDomain: 'turismapp-776f3.firebaseapp.com',
    storageBucket: 'turismapp-776f3.appspot.com',
    measurementId: 'G-MJD126DZXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaGm19oZ5Ge-BW6iTbhD1PwWPwnySA48o',
    appId: '1:686535225133:android:e28cc07f3f3c99d1aaada4',
    messagingSenderId: '686535225133',
    projectId: 'turismapp-776f3',
    storageBucket: 'turismapp-776f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIOX9twtLKv_TOUmTBp2PICz_a7q9J_Ag',
    appId: '1:686535225133:ios:db4e3dbef9005d3aaaada4',
    messagingSenderId: '686535225133',
    projectId: 'turismapp-776f3',
    storageBucket: 'turismapp-776f3.appspot.com',
    iosClientId: '686535225133-gnoqr594lhrl04g23h704m87v7hpc8sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.registrarPageTurismapp',
  );
}
